"""Conversation analysis and profiling service."""

from dataclasses import dataclass, field
import re

from app.domain.conversation import Conversation


@dataclass
class ConversationProfile:
    """Analytical profile generated by inspecting a conversation."""

    total_messages: int
    user_messages_count: int
    assistant_messages_count: int
    code_blocks_count: int
    code_ratio: float
    question_prompts_count: int
    has_quiz_patterns: bool
    has_debugging_patterns: bool
    has_business_patterns: bool
    has_research_patterns: bool
    has_meeting_patterns: bool
    detected_topics: list[str] = field(default_factory=list)
    primary_intent_keywords: list[str] = field(default_factory=list)


class ConversationAnalyzer:
    """Analyze full conversation history to produce an intelligence profile."""

    def analyze(self, conversation: Conversation) -> ConversationProfile:
        """Inspect all turns and extract analytical signals."""
        messages = conversation.messages
        total = len(messages)
        user_msgs = [m for m in messages if str(m.role).lower() == "user"]
        assistant_msgs = [m for m in messages if str(m.role).lower() == "assistant"]

        full_text = "\n".join(m.plain_text for m in messages)
        code_blocks = re.findall(r"```[\s\S]*?```", full_text)
        code_char_len = sum(len(cb) for cb in code_blocks)
        total_char_len = max(len(full_text), 1)
        code_ratio = code_char_len / total_char_len

        has_quiz = bool(re.search(r"(?:check\s*for\s*understanding|quiz|test\s*your|questions?:|spot\s*on)", full_text, re.I))
        has_debug = bool(re.search(r"(?:error|exception|traceback|fix|bug|issue|failed|crash|syntaxerror)", full_text, re.I))
        has_biz = bool(re.search(r"(?:market|revenue|business|competitor|strategy|pricing|customer|saas)", full_text, re.I))
        has_research = bool(re.search(r"(?:paper|study|hypothesis|evidence|finding|literature|source|citation)", full_text, re.I))
        has_meeting = bool(re.search(r"(?:agenda|meeting|decision|action\s*item|deadline|attendee|minutes)", full_text, re.I))

        # Extract explicit topic headings
        detected_topics = re.findall(r"^(?:#{1,4}\s+)?(Topic\s+\d+:[^\n]+)", full_text, re.M | re.I)

        return ConversationProfile(
            total_messages=total,
            user_messages_count=len(user_msgs),
            assistant_messages_count=len(assistant_msgs),
            code_blocks_count=len(code_blocks),
            code_ratio=code_ratio,
            question_prompts_count=len(user_msgs),
            has_quiz_patterns=has_quiz,
            has_debugging_patterns=has_debug,
            has_business_patterns=has_biz,
            has_research_patterns=has_research,
            has_meeting_patterns=has_meeting,
            detected_topics=detected_topics,
        )
